_BASE_: "FCSGG-Base.yaml"
MODEL:
  SIZE_DIVISIBILITY: 64
  META_ARCHITECTURE: "CenterNet"
  HRNET:
    WEIGHTS: "output/FasterR-CNN-HR32-3x.pth"
    FINAL_STAGE_MULTISCALE: True
    NORM: "SyncBN"
    UPSAMPLE_MODE: "bilinear"
  BACKBONE:
    NAME: "build_hrnet_backbone"
  NECKS:
    ENABLED: True
    NAME: HRFPN
    IN_FEATURES: [ "hr2", "hr3", "hr4", "hr5" ]
    OUT_CHANNELS: [ 256 ]
    UPSAMPLE_MODE: "bilinear"
    NORM: "SyncBN"
  HEADS:
    NAME: MultiScaleSwitchNormHeads
    CONV_DIM: 128
    NUM_CONV: 4
    NORM: "SyncBN"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    OUTPUT_STRIDES: [ 4, 8, 16, 32 ]
    LOSS:
      WH_WEIGHT: 0.1
    RAF:
      DOWN_SAMPLE_RATIO: 2
      CONV_DIM: 256
      NUM_CONV: 4
RELATION:
  RELATION_ON: True
INPUT:
  GT_SCALE_AWARE: True
  GT_REGRESSION_SCALE_AWARE: False
  CENTER_GAUSSIAN_IOU_MIN_OVERLAPS: [0.5, 0.5, 0.5, 0.5]
SOLVER:
  IMS_PER_BATCH: 48
  BASE_LR: 0.0005 # linear scale these
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 100
  STEPS: (30000, 60000) # linear scale these
  MAX_ITER: 90000 # linear scale these
OUTPUT_DIR: "./output/vg/fcsgg_hrnet_w32_hrfpn_512x512_ms"
